name: Notificar a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: 🚨 Notificación a ntfy.sh
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Clonar el código
        uses: actions/checkout@v3

      - name: 🧪 Ejecutar Hola Mundo
        run: |
          echo "✅ Hola Mundo ejecutado desde index.js"
          node index.js

      - name: 🚀 Enviar notificación a ntfy.sh
        env:
          NTFY_TOPIC: devops-itla
        run: |
          echo "📢 Enviando notificación a ntfy..."
          curl -s \
            -X POST \
            -d "✅ Se ha hecho push a main en el repo $GITHUB_REPOSITORY 🚀" \
            https://ntfy.sh/$NTFY_TOPIC
